%% ログイン要求

sequenceDiagram
  %%actor user
  participant localFunc
  participant clientMail
  %%participant encryptRequest
  participant IndexedDB
  participant authClient
  participant authServer
  participant memberList
  %%participant decryptRequest
  %%participant serverFunc
  actor admin

  localFunc->>+authClient: 処理要求
  Note right of authClient: 要求前準備(メイン処理)

  loop 処理要求中フラグ === true && 処理回数 < パスコード入力の最大試行回数

    alt ⑨未ログイン

      rect rgba(209, 247, 221, 1)
        Note right of authClient: requestLogin()

        alt ログイン試行中フラグ === false

          authClient->>authClient: ログイン試行中フラグ=true
          authClient->>+authServer: ログイン要求
          Note right of authServer: loginTrial()
          memberList->>authServer: 状態確認
          alt アカウント有効かつパスコード未通知
            authServer->>clientMail: パスコード通知メール
          end
          alt 待機時間内にauthServerから返信無し
            authClient->>authClient: ⑩result==='fatal'
          else 待機時間内にauthServerから返信あり
            authServer->>-authClient: 確認結果通知
            alt result==='warning'
              authClient->>authClient: warning処理
            end
          end

        else ログイン試行中フラグ === true
        
          clientMail->>authClient: パスコード入力
          authClient->>authServer: パスコード
          authServer->>authServer: パスコード確認
          alt 待機時間内にauthServerから返信無し
            authClient->>authClient: ⑩result==='fatal'
          else 待機時間内にauthServerから返信あり
            authServer->>authClient: 確認結果通知
            alt result==='warning'
              authClient->>authClient: warning処理
            else result==='success'
              authClient->>authClient: ⑪ログイン時処理
            end
          end
        end
      end
    end
  end

  authClient->>-localFunc: 処理結果