sequenceDiagram
  autonumber
  participant html
  participant ap as application
  participant st as Storage
  participant db as alaSQL
  participant cl as authClient
  participant sv as authServer
  participant sp as SpreadDb
  participant sh as Google Spread

%% ゲストとしてのアクセス

html ->> ap : 表示要求
ap ->> cl : 情報要求 ※1
  %%※1: 表示するページに必要な情報を要求するクエリ(ex.掲示板のやりとり)
cl ->> st : 資格情報参照　※2
  %%※2: userId, CPkeyをブラウザのlocal/sessionStorageから取得できないか試行。<br>なおゲストなので空振りするはず(何れも存在しない)
cl ->> sv : 情報要求 ※3
  %%※3: クエリのみ(userId, CPkeyともに無し)
sv ->> sv : 資格確認 ※4
  %%※4: userIdが無いのでゲストと判断
sv ->> sp : クエリ実行 ※5
  %%※5: SpreadDbにクエリを送信。SpreadDbはゲスト権限で許容されるクエリかを判断、結果をauthServerに送信
sv ->> cl : クエリ実行結果 ※6
  %%※6: 掲示板のやりとり等、ゲストに提供できる情報のみを返信
cl ->> ap : 情報提供
ap ->> html : 表示

%% 注釈のみ残す正規表現：^(?!\s*%%※).*\n+
