sequenceDiagram
  autonumber
  participant html
  participant ap as application
  participant st as Storage
  participant db as alaSQL
  participant cl as authClient
  participant sv as authServer
  participant sp as SpreadDb
  participant sh as Google Spread

%% メンバ登録(フォーム)
html ->> ap : 登録要求
ap ->> st : isReg参照
alt isReg=false(サーバ側にメアド未登録)
  ap ->> html : ダイアログ
  html ->> ap : メアド
end
ap ->> cl : userId(+email)
cl ->> sv : userId(+email)
sv ->> sp : ユーザ情報要求
sv ->> html : パスコード通知メール
sv ->> cl : パスコード要求
cl ->> html : ダイアログ
html ->> cl : パスコード
cl ->> sv : パスコード
sv ->> sv : 検証
sv ->> cl : OK
cl ->> ap : OK

ap ->> html : フォーム
html ->> ap : ユーザ情報
ap ->> cl : ユーザ情報
cl ->> sv : ユーザ情報更新要求
sv ->> sp : ユーザ情報更新要求
sp ->> sh : ユーザ情報