sequenceDiagram
  participant localStorage
  participant authClient
  participant authServer
  participant memberList
  participant admin

  authServer->>authServer: ①公開鍵の準備
  authClient->>authServer: 加入要求
  authServer->>authClient: SPkey(平文)
  localStorage->>authClient: ②鍵ペアの準備
  authClient->>authClient: メールアドレス入力
  authClient->>authServer: メールアドレス
  authServer->>memberList: メールアドレスとCPkey送信、保管
  authServer->>admin: 加入要求連絡
  admin->>authServer: ③加入可否検討
  authServer->>authClient: ④結果連絡

