// ----- Auth/1.1.0/test.js generated by build.sh ---------------------
const dev = devTools();
const authTest = () => doTest('dev',0,1); // 引数はscenario, start, num
//::$src/doTest.js::

//::$src/authCommon.js::

//::$src/authClient.js::

//::$src/authServer.js::

function authPost(arg) {
  const v = { whois: 'authPost', rv: null};
  // whois: `${pv.whois}.prototype`, rv: null};
  // whois: this.constructor.name+'.prototype', rv: null};
  dev.start(v.whois, [...arguments]);
  try {

    // -------------------------------------------------------------
    dev.step(1); // 引数の存否確認、データ型チェック ＋ ワークの準備
    // -------------------------------------------------------------
    v.rv = authServer(arg);

    dev.end(); // 終了処理
    return v.rv;

  } catch (e) { dev.error(e); return e; }
}

//::$lib/createPassword/1.0.1/core.js::
//::$lib/devTools/1.0.0/core.js::
//::$lib/isEqual/1.1.0/core.js::
//::$lib/SpreadDb/1.2.0/core.js::
//::$lib/toLocale/1.1.0/core.js::
//::$lib/whichType/1.0.1/core.js::
